# Generated by Django 3.2.25 on 2024-07-11 06:59

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CreatedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FlowerMaterial',
            fields=[
                ('model', models.CharField(default='Material0000', max_length=100, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('chinese_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('english_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('scientific_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('size', models.FloatField(blank=True, default=0.0, help_text='单位：cm')),
                ('weight', models.FloatField(blank=True, default=0.0, help_text='单位：g')),
                ('sale_spec_quantity', models.FloatField(blank=True, default=0.0, help_text='数量')),
                ('sale_spec_unit', models.CharField(blank=True, choices=[('pcs', 'pcs'), ('g', 'g'), ('box', 'box'), ('kg', 'kg')], default='pcs', max_length=10, null=True)),
                ('outer_box_length', models.FloatField(blank=True, default=0.0, help_text='长度，单位：cm', null=True)),
                ('outer_box_width', models.FloatField(blank=True, default=0.0, help_text='宽度，单位：cm', null=True)),
                ('outer_box_height', models.FloatField(blank=True, default=0.0, help_text='高度，单位：cm', null=True)),
                ('packing_quantity', models.IntegerField(blank=True, default=0, help_text='单位：qty', null=True)),
                ('price_one', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('price_two', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('category', models.ForeignKey(default='默认类型', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.category')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.createdby')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('model', models.CharField(default='Product0000', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('chinese_name', models.CharField(max_length=200)),
                ('english_name', models.CharField(max_length=200)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('loss_rate', models.FloatField(default=0.0)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.createdby')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1.0)),
                ('ratio', models.FloatField(default=1.0)),
                ('price_type', models.CharField(choices=[('price_one', 'Price One'), ('price_two', 'Price Two')], default='price_one', max_length=10)),
                ('flower_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.flowermaterial')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(through='app01.ProductMaterial', to='app01.FlowerMaterial'),
        ),
        migrations.AddField(
            model_name='flowermaterial',
            name='grade',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.grade'),
        ),
        migrations.AddField(
            model_name='flowermaterial',
            name='process',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.process'),
        ),
        migrations.AddField(
            model_name='flowermaterial',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.supplier'),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
