# Generated by Django 4.1 on 2024-07-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=200)),
                ("picture", models.ImageField(upload_to="products/")),
                ("specification", models.TextField()),
                (
                    "COLOR",
                    models.CharField(
                        choices=[("red", "红色"), ("blue", "蓝色"), ("green", "绿色")],
                        max_length=200,
                    ),
                ),
                ("qty", models.IntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
