# Generated by Django 3.2.25 on 2024-07-07 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, unique=True, verbose_name='型号')),
                ('name', models.CharField(max_length=100, verbose_name='品名')),
                ('size', models.CharField(max_length=50, verbose_name='尺寸')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='重量')),
                ('packing_dimension', models.CharField(max_length=100, verbose_name='包装规格')),
                ('packing_qty', models.IntegerField(verbose_name='包装数量')),
                ('purchase_spe', models.CharField(max_length=100, verbose_name='购买时的规格')),
                ('usage_spe', models.CharField(max_length=100, verbose_name='使用时的规格')),
                ('grade', models.CharField(max_length=50, verbose_name='等级')),
                ('stock', models.IntegerField(verbose_name='库存')),
            ],
            options={
                'verbose_name': '花材',
                'verbose_name_plural': '花材',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='生产方式名称')),
            ],
            options={
                'verbose_name': '生产方式',
                'verbose_name_plural': '生产方式',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='系列名称')),
            ],
            options={
                'verbose_name': '系列',
                'verbose_name_plural': '系列',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='供应商名称')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('flower_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.flowermaterial', verbose_name='花材')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '供应商价格',
                'verbose_name_plural': '供应商价格',
                'unique_together': {('supplier', 'flower_material')},
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='flowermaterial',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.process', verbose_name='生产方式'),
        ),
        migrations.AddField(
            model_name='flowermaterial',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.series', verbose_name='系列'),
        ),
    ]
