# Generated by Django 3.2.25 on 2024-07-11 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Created_by',
            new_name='CreatedBy',
        ),
    ]
