# Generated by Django 5.0.7 on 2024-07-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Package",
            field=models.CharField(blank=True, default="默认包装", max_length=200),
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(blank=True, default="默认颜色", max_length=200),
        ),
        migrations.AddField(
            model_name="product",
            name="inner_box_height",
            field=models.FloatField(
                blank=True, default=0.0, help_text="长度，单位：cm", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="inner_box_long",
            field=models.FloatField(
                blank=True, default=0.0, help_text="长度，单位：cm", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="inner_box_width",
            field=models.FloatField(
                blank=True, default=0.0, help_text="长度，单位：cm", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="outer_box_height",
            field=models.FloatField(
                blank=True, default=0.0, help_text="高度，单位：cm", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="outer_box_length",
            field=models.FloatField(
                blank=True, default=0.0, help_text="长度，单位：cm", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="outer_box_width",
            field=models.FloatField(
                blank=True, default=0.0, help_text="宽度，单位：cm", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(blank=True, default="0", max_length=200),
        ),
        migrations.AddField(
            model_name="product",
            name="weigth",
            field=models.CharField(blank=True, default="0", max_length=200),
        ),
    ]
