# Generated by Django 5.0.7 on 2024-07-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="status",
            field=models.CharField(
                choices=[
                    ("跟进中", "跟进中"),
                    ("已付款", "已付款"),
                    ("已成交", "已成交"),
                    ("已放弃", "已放弃"),
                ],
                default="跟进中",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="preparation_status",
            field=models.CharField(
                choices=[
                    ("not_started", "未开始"),
                    ("in_progress", "备货中"),
                    ("completed", "已完成"),
                ],
                default="not_started",
                max_length=20,
                verbose_name="备货状态",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("unpaid", "未付款"),
                    ("paid", "已付款"),
                    ("shipped", "已发货"),
                    ("signed", "已签收"),
                    ("completed", "已完成"),
                    ("closed", "已关闭"),
                ],
                default="pending",
                max_length=10,
                verbose_name="订单状态",
            ),
        ),
    ]
