# Generated by Django 3.2.25 on 2024-07-08 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20240707_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='supplierprice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='supplierprice',
            name='flower_material',
        ),
        migrations.RemoveField(
            model_name='supplierprice',
            name='supplier',
        ),
        migrations.AlterModelOptions(
            name='flowermaterial',
            options={},
        ),
        migrations.AlterModelOptions(
            name='process',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={},
        ),
        migrations.RemoveField(
            model_name='flowermaterial',
            name='name',
        ),
        migrations.RemoveField(
            model_name='flowermaterial',
            name='packing_dimension',
        ),
        migrations.RemoveField(
            model_name='flowermaterial',
            name='packing_qty',
        ),
        migrations.RemoveField(
            model_name='flowermaterial',
            name='purchase_spe',
        ),
        migrations.RemoveField(
            model_name='flowermaterial',
            name='series',
        ),
        migrations.RemoveField(
            model_name='flowermaterial',
            name='usage_spe',
        ),
        migrations.AddField(
            model_name='flowermaterial',
            name='chinese_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flowermaterial',
            name='english_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flowermaterial',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flowermaterial',
            name='outer_box_height',
            field=models.FloatField(default=1, help_text='高度，单位：cm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flowermaterial',
            name='outer_box_length',
            field=models.FloatField(default=1, help_text='长度，单位：cm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flowermaterial',
            name='outer_box_width',
            field=models.FloatField(default=1, help_text='宽度，单位：cm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flowermaterial',
            name='packing_quantity',
            field=models.IntegerField(default=1, help_text='单位：qty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flowermaterial',
            name='price_one',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flowermaterial',
            name='price_two',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flowermaterial',
            name='sale_spec_quantity',
            field=models.FloatField(default=11, help_text='数量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flowermaterial',
            name='sale_spec_unit',
            field=models.CharField(choices=[('pcs', 'pcs'), ('g', 'g'), ('box', 'box'), ('kg', 'kg')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flowermaterial',
            name='scientific_name',
            field=models.CharField(default=11, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flowermaterial',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.supplier'),
        ),
        migrations.AlterField(
            model_name='flowermaterial',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1),
        ),
        migrations.AlterField(
            model_name='flowermaterial',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flowermaterial',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.process'),
        ),
        migrations.AlterField(
            model_name='flowermaterial',
            name='size',
            field=models.FloatField(help_text='单位：cm'),
        ),
        migrations.AlterField(
            model_name='flowermaterial',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flowermaterial',
            name='weight',
            field=models.FloatField(help_text='单位：g'),
        ),
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Series',
        ),
        migrations.DeleteModel(
            name='SupplierPrice',
        ),
        migrations.AddField(
            model_name='flowermaterial',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.category'),
        ),
        migrations.AddField(
            model_name='flowermaterial',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.color'),
        ),
    ]
