# Generated by Django 5.0.7 on 2024-08-01 07:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0002_alter_customer_status_alter_order_preparation_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreparationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("needless", "不需要采购"),
                            ("needed", "需要采购"),
                            ("simple_purchase_order", "收到简单采购单"),
                            ("purchase_order_completed", "采购单完成"),
                            ("in_purchase", "正在采购"),
                            ("stored", "已采购入库"),
                            ("purchase_completed", "采购完成"),
                        ],
                        max_length=100,
                        unique=True,
                        verbose_name="状态名称",
                    ),
                ),
            ],
            options={
                "verbose_name": "采购状态",
                "verbose_name_plural": "采购状态",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app01.shippingmethod",
                verbose_name="发货方式",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("unpaid", "未付款"),
                    ("paid", "已付款"),
                    ("shipped", "已发货"),
                    ("signed", "已签收"),
                    ("completed", "已完成"),
                    ("closed", "已关闭"),
                ],
                default="unpaid",
                max_length=10,
                verbose_name="订单状态",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="tracking_number",
            field=models.TextField(blank=True, null=True, verbose_name="填写运单号"),
        ),
        migrations.AlterField(
            model_name="order",
            name="preparation_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app01.preparationstatus",
                verbose_name="采购状态",
            ),
        ),
        migrations.CreateModel(
            name="StockFlowerMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(max_length=100, unique=True, verbose_name="批次号"),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="颜色"
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="尺寸"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0, verbose_name="数量")),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10, verbose_name="成本价"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "flower_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.flowermaterial",
                        verbose_name="花材",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_type",
                    models.CharField(
                        choices=[
                            ("flower_material", "花材"),
                            ("product", "产品"),
                            ("packaging", "包装"),
                        ],
                        max_length=20,
                        verbose_name="库存类型",
                    ),
                ),
                (
                    "in_type",
                    models.CharField(
                        choices=[("purchase", "采购入库"), ("production", "生产入库")],
                        max_length=20,
                        verbose_name="入库类型",
                    ),
                ),
                ("stock_item_id", models.PositiveIntegerField(verbose_name="库存项目ID")),
                ("batch_number", models.CharField(max_length=100, verbose_name="批次号")),
                ("quantity", models.PositiveIntegerField(verbose_name="数量")),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="成本价"
                    ),
                ),
                (
                    "in_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="入库日期"
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="经办人",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_type",
                    models.CharField(
                        choices=[
                            ("flower_material", "花材"),
                            ("product", "产品"),
                            ("packaging", "包装"),
                        ],
                        max_length=20,
                        verbose_name="库存类型",
                    ),
                ),
                (
                    "out_type",
                    models.CharField(
                        choices=[("sales", "销售出库"), ("production", "生产出库")],
                        max_length=20,
                        verbose_name="出库类型",
                    ),
                ),
                ("stock_item_id", models.PositiveIntegerField(verbose_name="库存项目ID")),
                ("batch_number", models.CharField(max_length=100, verbose_name="批次号")),
                ("quantity", models.PositiveIntegerField(verbose_name="数量")),
                (
                    "out_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="出库日期"
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="经办人",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockPackaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(max_length=100, unique=True, verbose_name="批次号"),
                ),
                ("quantity", models.PositiveIntegerField(default=0, verbose_name="数量")),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10, verbose_name="成本价"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "packaging",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.packaging",
                        verbose_name="包装",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(max_length=100, unique=True, verbose_name="批次号"),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="颜色"
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="尺寸"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0, verbose_name="数量")),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10, verbose_name="成本价"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.product",
                        verbose_name="产品",
                    ),
                ),
            ],
        ),
    ]
