# Generated by Django 3.2.25 on 2024-07-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_remove_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowermaterial',
            name='size',
            field=models.CharField(blank=True, default='', help_text='单位：cm', max_length=200),
        ),
        migrations.AlterField(
            model_name='flowermaterial',
            name='weight',
            field=models.CharField(blank=True, default='', help_text='单位：g', max_length=200),
        ),
    ]
