# Generated by Django 5.0.7 on 2024-07-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0002_product_package_product_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sale_spec_quantity",
            field=models.CharField(
                blank=True, default="", help_text="销售规格的数字", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sale_spec_unit",
            field=models.CharField(
                blank=True,
                choices=[("box", "box"), ("pcs", "pcs"), ("g", "g"), ("kg", "kg")],
                default="box",
                help_text="销售规格的单位",
                max_length=10,
                null=True,
            ),
        ),
    ]
