# Generated by Django 5.0.7 on 2024-07-19 05:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0003_product_sale_spec_quantity_product_sale_spec_unit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="weigth",
            new_name="weight",
        ),
    ]
