# Generated by Django 5.0.7 on 2024-08-01 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0003_preparationstatus_alter_order_shipping_method_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockflowermaterial",
            name="cost_price",
        ),
        migrations.RemoveField(
            model_name="stockpackaging",
            name="cost_price",
        ),
        migrations.RemoveField(
            model_name="stockproduct",
            name="cost_price",
        ),
    ]
