# Generated by Django 5.0.7 on 2024-07-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0004_rename_weigth_product_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="products/"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(blank=True, default="无备注", max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="inner_box_height",
            field=models.FloatField(
                blank=True, default=0.0, help_text="高度，单位：cm", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="inner_box_width",
            field=models.FloatField(
                blank=True, default=0.0, help_text="宽度，单位：cm", null=True
            ),
        ),
    ]
