# Generated by Django 3.2.25 on 2024-07-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20240712_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowermaterial',
            name='sale_spec_quantity',
            field=models.CharField(blank=True, default='', help_text='销售规格的数字', max_length=200),
        ),
        migrations.AlterField(
            model_name='flowermaterial',
            name='sale_spec_unit',
            field=models.CharField(blank=True, choices=[('pcs', 'pcs'), ('g', 'g'), ('box', 'box'), ('kg', 'kg')], default='pcs', help_text='销售规格的单位', max_length=10, null=True),
        ),
    ]
