# Generated by Django 5.0.7 on 2024-07-22 05:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0005_product_image_alter_product_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "shipper",
                    models.CharField(default="Summer Flora.Co.,Ltd.", max_length=255),
                ),
                ("buyer", models.CharField(max_length=255)),
                ("receiver", models.CharField(max_length=255)),
                ("tel", models.CharField(max_length=20)),
                ("invoice_no", models.CharField(max_length=50)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("valid_date", models.DateField()),
                (
                    "freight_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "payment_term",
                    models.CharField(
                        default="100% payment in advance.", max_length=100
                    ),
                ),
                (
                    "deliver_time",
                    models.CharField(
                        default="7-15 working days after confirm of payment.",
                        max_length=100,
                    ),
                ),
                ("payment_currency", models.CharField(default="USD", max_length=10)),
                (
                    "beneficiary_account_number",
                    models.CharField(default="101417 09988447", max_length=50),
                ),
                ("swift_code", models.CharField(default="CHASSGSGXXX", max_length=11)),
                (
                    "beneficiary_country",
                    models.CharField(default="Singapore", max_length=50),
                ),
                (
                    "beneficiary_name",
                    models.CharField(
                        default="Yunnan Summer Flora Co., Ltd.", max_length=100
                    ),
                ),
                (
                    "beneficiary_address",
                    models.CharField(
                        default="8 Shenton Way, #45-01, AXA Tower, Singapore 068811",
                        max_length=255,
                    ),
                ),
                (
                    "beneficiary_bank",
                    models.CharField(
                        default="JPMorgan Chase Bank N.A., Singapore Branch J.BMorgan",
                        max_length=100,
                    ),
                ),
                (
                    "beneficiary_bank_address",
                    models.CharField(
                        default="168 Robinson Road, Capital Tower 17-00, Singapore 068912",
                        max_length=255,
                    ),
                ),
                ("bank_code", models.CharField(default="7153", max_length=10)),
                ("branch_code", models.CharField(default="1", max_length=10)),
                ("remark", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(editable=False)),
                ("updated_at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                (
                    "picture",
                    models.ImageField(blank=True, null=True, upload_to="quote_items/"),
                ),
                ("specification", models.CharField(max_length=200)),
                ("color", models.CharField(max_length=100)),
                ("qty", models.PositiveIntegerField(default=1)),
                ("cost_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "profit_margin",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="app01.quote",
                    ),
                ),
            ],
        ),
    ]
