# Generated by Django 3.2.25 on 2024-07-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20240715_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowermaterial',
            name='chineses_specifications',
            field=models.CharField(blank=True, default='无中文规格', max_length=200, null=True),
        ),
    ]
