# Generated by Django 5.0.7 on 2024-07-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0006_quote_quoteitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="bank_code",
            field=models.CharField(default=" ", max_length=10),
        ),
        migrations.AlterField(
            model_name="quote",
            name="beneficiary_account_number",
            field=models.CharField(default=" ", max_length=50),
        ),
        migrations.AlterField(
            model_name="quote",
            name="beneficiary_address",
            field=models.CharField(default=" ", max_length=255),
        ),
        migrations.AlterField(
            model_name="quote",
            name="beneficiary_bank",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="quote",
            name="beneficiary_bank_address",
            field=models.CharField(default=" ", max_length=255),
        ),
        migrations.AlterField(
            model_name="quote",
            name="beneficiary_country",
            field=models.CharField(default=" ", max_length=50),
        ),
        migrations.AlterField(
            model_name="quote",
            name="branch_code",
            field=models.CharField(default=" ", max_length=10),
        ),
        migrations.AlterField(
            model_name="quote",
            name="deliver_time",
            field=models.CharField(default=" ", max_length=100),
        ),
        migrations.AlterField(
            model_name="quote",
            name="payment_term",
            field=models.CharField(default=" ", max_length=100),
        ),
        migrations.AlterField(
            model_name="quote",
            name="remark",
            field=models.TextField(blank=True, default=" "),
        ),
        migrations.AlterField(
            model_name="quote",
            name="swift_code",
            field=models.CharField(default=" ", max_length=11),
        ),
    ]
