# Generated by Django 5.0.7 on 2024-07-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0007_alter_quote_bank_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowermaterial",
            name="cost_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
