# Generated by Django 5.0.7 on 2024-07-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0008_flowermaterial_cost_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmaterial",
            name="price_type",
        ),
        migrations.AddField(
            model_name="product",
            name="profit_margin",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
