# Generated by Django 5.0.7 on 2024-07-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0013_remove_followuprecord_attachment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="customer_images/"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="level",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                default="A",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="social_account",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="website_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
