# Generated by Django 5.0.7 on 2024-07-25 08:13

import app01.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0015_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="Package",
        ),
        migrations.AddField(
            model_name="product",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to=app01.models.product_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=app01.models.product_directory_path,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app01.producttype",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="package",
            field=models.CharField(blank=True, default="默认包装", max_length=200),
        ),
    ]
