# Generated by Django 5.0.7 on 2024-07-26 06:30

import app01.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0016_producttype_remove_product_package_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackagingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Packaging",
            fields=[
                (
                    "model",
                    models.CharField(
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=app01.models.packaging_directory_path,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "length",
                    models.FloatField(blank=True, help_text="长度，单位：cm", null=True),
                ),
                (
                    "width",
                    models.FloatField(blank=True, help_text="宽度，单位：cm", null=True),
                ),
                (
                    "height",
                    models.FloatField(blank=True, help_text="高度，单位：cm", null=True),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("remark", models.TextField(blank=True, default="无备注")),
                ("created_at", models.DateTimeField(editable=False)),
                ("updated_at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "packaging_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app01.packagingtype",
                    ),
                ),
            ],
        ),
    ]
