# Generated by Django 5.0.7 on 2024-07-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0017_packagingtype_packaging"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagingtype",
            name="name",
            field=models.CharField(
                choices=[
                    ("内盒", "Inner Box"),
                    ("外箱", "Outer Box"),
                    ("花器", "Flower Vessel"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
    ]
