# Generated by Django 5.0.7 on 2024-07-26 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0018_alter_packagingtype_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="inner_box_height",
        ),
        migrations.RemoveField(
            model_name="product",
            name="inner_box_long",
        ),
        migrations.RemoveField(
            model_name="product",
            name="inner_box_width",
        ),
        migrations.RemoveField(
            model_name="product",
            name="outer_box_height",
        ),
        migrations.RemoveField(
            model_name="product",
            name="outer_box_length",
        ),
        migrations.RemoveField(
            model_name="product",
            name="outer_box_width",
        ),
        migrations.RemoveField(
            model_name="product",
            name="package",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sale_spec_quantity",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sale_spec_unit",
        ),
        migrations.CreateModel(
            name="ProductPackaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inner_box_quantity",
                    models.PositiveIntegerField(
                        blank=True, default=0, help_text="一个内箱能装多少个产品", null=True
                    ),
                ),
                (
                    "outer_box_quantity",
                    models.PositiveIntegerField(
                        blank=True, default=0, help_text="一个大外箱能装多少内箱", null=True
                    ),
                ),
                (
                    "packaging",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.packaging",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.product"
                    ),
                ),
            ],
        ),
    ]
